version: "3.5"
services:
  db:
    container_name: mysql_db_c
    image: mysql
    volumes:
      - ./db/db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: cloud-1
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
  wp:
    container_name: wordpress_c
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./wp/wordpress_data:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: userpass
      WORDPRESS_DB_NAME: cloud-1
  phpmyadmin:
    container_name: phpmyadmin_c
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db