---
  - name: deploy
    hosts: azure_vm
    remote_user: azureuser
    become: yes
    roles:
      - setup_env
      - copy_files
      - restore_AppVolumes
      - build_images
      - clean_OldContainers
      - setup_DockerNetwork
      - run_containers
      - adapt_ip