---
  - name: deploy
    hosts: azure_vm
    remote_user: azureuser
    become: yes
    tasks:
    - name: apt update
      apt:
        update_cache: yes
    - name: apt install python {{inventory_hostname}}
      apt:
        name: python
        state: latest
    - name: install curl
      apt:
        name: curl
        state: latest

    - name: curl get.docker.com 
      command: curl -fsSL get.docker.com -o get-docker.sh

    - name: install docker
      command: sudo sh get-docker.sh

    - name: cleanup get-docker.sh
      command: rm get-docker.sh
