---
# tasks file for clean_OldContainers
- name: remove container cloud-1_mysql
  docker_container:
    name: cloud-1_mysql
    state: absent
  tags:
    - stop_all
    - stop_mysql
    - restart_mysql

- name: remove container cloud-1_wordpress
  docker_container:
    name: cloud-1_wordpress
    state: absent
  tags:
    - stop_all
    - stop_wp
    - restart_wp

- name: remove container cloud-1_phpmyadmin
  docker_container:
    name: cloud-1_phpmyadmin
    state: absent
  tags:
    - stop_all
    - stop_pma
    - restart_pma

- name: Delete network cloud-1_net
  docker_network:
    name: cloud-1_net
    state: absent
    force: yes