---
# tasks file for setup_env
- name: apt update
  apt:
    update_cache: yes

- name: apt install python {{inventory_hostname}}
  apt:
    name: python
    state: latest

- name: install curl
  apt:
    name: curl
    state: latest

- name: Curl get.docker.com 
  command: curl -fsSL get.docker.com -o get-docker.sh

- name: Install docker
  command: sudo sh get-docker.sh

- name: Cleanup get-docker.sh
  command: rm get-docker.sh

- name: Install python3-pip
  apt:
    name: python3-pip
    state: latest

- name: Install docker SDK
  command: pip install docker